version: '2'
services :
  web :
    build : .
    links :
      - db
    ports :
      - 80:80
      - 443:443
    volumes :
      - ./www:/var/www/html
  db :
    image : mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD : test
      MYSQL_DATABASE : ocsweb
      MYSQL_USER : ocs
      MYSQL_PASSWORD : ocsweb
    volumes :
      - ./sql/:/docker-entrypoint-initdb.d/
    ports :
      - 3306:3306
